options {
    directory "/var/cache/bind";
    recursion yes;
    allow-recursion { any; };
    listen-on { any; };
    listen-on-v6 { any; };
    forwarders {
        8.8.8.8;
        1.1.1.1;
    };
    dnssec-validation auto;
    allow-transfer { none; };
};

include "/etc/bind/rndc.key";

controls {
    inet * port 953 allow { any; } keys { "rndc-key"; };
};

include "/etc/bind/named.conf.local";
